server.port=${PORT:8080}

# Database Configuration (Neon PostgreSQL Cloud DB)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://ep-curly-moon-ayqaouk1-pooler.c-5.us-east-2.aws.neon.tech/neondb?sslmode=require}
spring.datasource.driverClassName=${SPRING_DATASOURCE_DRIVER:org.postgresql.Driver}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:neondb_owner}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:npg_A9toGsnrJyW8}

# JPA / Hibernate properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Cloudinary Cloud Storage Configuration
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME:dpki2zylo}
cloudinary.api-key=${CLOUDINARY_API_KEY:247935528979661}
cloudinary.api-secret=${CLOUDINARY_API_SECRET:-f4s1JgU9DWb0tRcGuX8Ej7Dgu0}

# Spring Boot File Upload Config
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Custom App Properties
logging.level.com.handmade.craft=INFO
